version: '3.10'


services:
  react:
    container_name: frontend-Parma
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
