version: '3.3'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
  db:
    image: postgres:15.0-alpine
    ports:
      - 5432:5432
    volumes:
      - dm_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ivan
      - POSTGRES_PASSWORD=ivan12345
      - POSTGRES_DB=Parma

volumes:
  dm_postgres_data:
