# Generated by Django 5.0.1 on 2024-02-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcodeemail',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='confirmationcodephone',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
