# Generated by Django 5.0.1 on 2024-02-07 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_place', to='map.place', verbose_name='Место'),
        ),
    ]
