# Generated by Django 5.0.2 on 2024-02-15 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.IntegerField(max_length=3, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Номер места'),
        ),
        migrations.AlterField(
            model_name='room',
            name='places',
            field=models.ManyToManyField(related_name='room', to='map.place', verbose_name='Места'),
        ),
    ]
