# Generated by Django 5.0.2 on 2024-02-27 14:38

import backend.map.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_place_name_alter_room_places'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationhistory',
            options={'ordering': ['-id'], 'verbose_name': 'История брони', 'verbose_name_plural': 'История брони'},
        ),
        migrations.AddField(
            model_name='place',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Отобразить?'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.IntegerField(unique=True, verbose_name='Номер места'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='place',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_place', to='map.place', validators=[backend.map.models.validate_empty_place], verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL, validators=[backend.map.models.validate_user_place], verbose_name='Сотрудник'),
        ),
    ]
