# Generated by Django 5.0.1 on 2024-02-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_place_status_reservationhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationhistory',
            old_name='ser',
            new_name='user',
        ),
    ]
