# Generated by Django 5.0.2 on 2024-02-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_reservationhistory_options_place_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(null=True, upload_to='place/', verbose_name='Фото места'),
        ),
    ]
