# Generated by Django 5.0.2 on 2024-02-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default='f', upload_to='place/', verbose_name='Фото места'),
        ),
    ]
