# Generated by Django 5.0.1 on 2024-02-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_reservationhistory_place_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationhistory',
            options={'verbose_name': 'История брони', 'verbose_name_plural': 'История брони'},
        ),
    ]
